name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Wordpress docker image
      run: |
        docker build . --file Dockerfile --tag dennisshum/wordpress
    - name: Docker push Wordpress
      run: |
        docker push dennisshum/wordpress
    - name: Build the MariaDB docker image
      run: |
        docker build . --file Dockerfile --tag dennisshum/mariadb
    - name: Docker push MariaDB
      run: |
        docker push dennisshum/mariadb
